// Auto-generated from the design panel's How-to-test plan. Data only — the page
// (HowToTest.tsx) maps each group to an icon and renders the guided tour.

export interface Mission {
  group: string;
  title: string;
  persona: string;
  route?: string;
  prompt?: string;
  lookFor: string;
}

export const TOUR_INTRO = "BuildRight AI is a real hardware store wired to a multi-agent assistant — and this is your guided lap, not a manual. Follow the missions top to bottom and you'll touch every headline feature in about six minutes: no setup, no dead ends, one Stripe test card. You'll start as a guest browsing the shelves, talk to the assistant until it surprises you, dig into a product's reviews and its recommendation graph, then log in as the manager to watch the machine's vitals. Everything is test data, Stripe is in test mode, and it re-seeds on every deploy — so click hard and break nothing. Tap any \"Try it\" to teleport straight there; tap \"Copy\" on a prompt and paste it into the chat.";

// AI-first ordering: visitors have no time — the agentic features open the tour;
// the classic e-commerce mechanics follow.
export const GROUP_ORDER: string[] = [
  "Chat with the AI assistant",
  "Multimodal & memory",
  "Reviews & the recommendation graph",
  "Manager intelligence (log in)",
  "Shop as a guest",
  "Checkout & orders",
  "Power features & access control"
];

export const MISSIONS: Mission[] = [
  { group: "Shop as a guest", title: "Browse, search & filter the storefront", persona: "Guest · no login", route: "/", lookFor: "37 hardware products in a responsive grid — type in the search box or pick a category and it filters instantly, with no empty or duplicate categories." },
  { group: "Shop as a guest", title: "Product imagery is generated SVG — zero photo files", persona: "Guest", route: "/item/circular-saw", lookFor: "Every 'photo' is a category-coloured vector drawn on the fly by the backend (accent hex + hand-built line icon + label) — 20 distinct styles, crisp at any zoom, no binary assets." },
  { group: "Shop as a guest", title: "Live stock status + star ratings on the detail page", persona: "Guest", route: "/item/mastercraft-drill", lookFor: "Real SKU, aggregate star rating, and a colour-coded badge that flips between In stock / Only N left / Out of stock — and options that re-price in real time." },
  { group: "Reviews & the recommendation graph", title: "Reviews + an AI 'What customers say' summary", persona: "Guest · can post a review", route: "/item/claw-hammer", lookFor: "A sparkle-badged AI blurb distilling all reviews with positive/critical counts and verified-purchase badges; post your own star review and watch the summary and average refresh." },
  { group: "Reviews & the recommendation graph", title: "GNN recommendations + a 'Why recommended?' graph", persona: "Guest", route: "/item/circular-saw", lookFor: "A 'You might also like' cross-sell rail, then a radial graph-neural-net neighbourhood — anchor in the centre, neighbours sized and linked by learned similarity; tap any node to walk the graph." },
  { group: "Chat with the AI assistant", title: "Grounded product search with add-to-cart cards", persona: "Guest", route: "/ · open chat ('Ask us', bottom-right)", prompt: "Do you have a cordless drill and how much is the cheapest one?", lookFor: "Real names + exact catalog prices and SKUs (never invented) rendered as product cards inside the reply, each with a one-tap 'Add' straight to the cart." },
  { group: "Chat with the AI assistant", title: "Live working-status indicators while it answers", persona: "Guest", route: "Chat widget · watch the bubble as it streams", prompt: "What's a good drill and what pairs with it?", lookFor: "Not a static spinner — the bubble narrates each phase over SSE: Thinking → Searching the catalog → Summarizing → Finalizing, then tokens stream in." },
  { group: "Chat with the AI assistant", title: "Guardrail: apologize + suggest an in-stock alternative", persona: "Guest", route: "Chat widget", prompt: "Do you sell a laser level?", lookFor: "For something it doesn't carry, it apologizes and offers the closest real alternative — never a fabricated product or price, because a deterministic price/citation check runs before any token renders." },
  { group: "Chat with the AI assistant", title: "RAG policy answer with a citation", persona: "Guest", route: "Chat widget", prompt: "What's your return policy for power tools?", lookFor: "An answer grounded in the policy/FAQ knowledge base and cited as 'Document › Section'; ask something off-policy and it routes you to customer service instead of guessing." },
  { group: "Chat with the AI assistant", title: "Buying-guide knowledge via hybrid RAG", persona: "Guest", route: "Chat widget", prompt: "What's the difference between an impact driver and a hammer drill?", lookFor: "A grounded, cited buying-guide answer fused from semantic + keyword search (Reciprocal Rank Fusion) over product knowledge — not a generic web answer." },
  { group: "Chat with the AI assistant", title: "In-chat recommendations (bought-with + similarity)", persona: "Guest", route: "Chat widget", prompt: "What goes well with a cordless drill?", lookFor: "Cross-sell picks from real co-purchase data plus content similarity, returned as add-to-cart product cards." },
  { group: "Chat with the AI assistant", title: "Conversational project planner with costed materials", persona: "Guest", route: "Chat widget", prompt: "I want to paint my bedroom, it's 12 by 10 feet with 8 foot walls. What do I need?", lookFor: "From your measurements it computes a materials list with real SKUs, quantities and a subtotal, then offers to add the whole list to the cart in one click — a 'COMPLEX' turn that escalates to the heavy model." },
  { group: "Chat with the AI assistant", title: "Shortlist hand-off: chat results → storefront", persona: "Guest", route: "Chat widget → /", prompt: "Show me your cheapest cordless drills under $150", lookFor: "After the answer a 'Show these N items on the storefront →' bar appears; click it to filter the homepage to exactly the assistant's picks with a sortable 'Shortlisted by the assistant' rail." },
  { group: "Multimodal & memory", title: "Image / photo product search (Claude vision)", persona: "Guest", route: "Chat widget · image button (bottom-left of input)", lookFor: "Upload a photo of a tool — it identifies the item ('I think that's a …') and lists matching in-stock products, which also become a storefront shortlist." },
  { group: "Multimodal & memory", title: "Voice ordering (Whisper speech-to-text)", persona: "Guest", route: "Chat widget · mic button", prompt: "Do you have a 20-volt cordless drill?", lookFor: "Tap mic, speak, tap stop: a 'Listening…' then 'Transcribing…' indicator, then your transcript flows into the normal grounded chat/reorder pipeline." },
  { group: "Multimodal & memory", title: "User memory — remembered preferences", persona: "Shopper · demo@buildright.com / Demo1234!", route: "/login → chat widget · 'Memory' button", prompt: "My preferred brand is Mastercraft. (then later) Recommend me a drill.", lookFor: "Saved preferences persist across turns and show as chips in the Memory panel; later answers respect the stored brand/tool preference." },
  { group: "Multimodal & memory", title: "Conversational CSAT rating", persona: "Guest", route: "Chat widget · after any reply", lookFor: "A 'How did I do?' 1–5 star prompt appears post-answer, and ratings flow straight into the Manager CSAT analytics (average, histogram, recent comments)." },
  { group: "Checkout & orders", title: "Cart + guest checkout + Stripe test payment", persona: "Guest · session-bound, IDOR-safe", route: "/checkout (add an item first)", lookFor: "Full checkout with no login — pay with Stripe test card 4242 4242 4242 4242 (any future expiry/CVC) and land on an order confirmation, all in test mode." },
  { group: "Checkout & orders", title: "Order history & one-line natural-language reorder", persona: "Shopper · demo@buildright.com / Demo1234!", route: "/orders", prompt: "Reorder my last paint order", lookFor: "Past orders with status; the chat 'reorder' tool re-adds a previous order's items from a plain-English reference, and chat-driven sales get attributed back to the assistant." },
  { group: "Manager intelligence (log in)", title: "Manager dashboard — inventory, margins, AI-attributed sales", persona: "Manager · manager@buildright.com / ManagerDemo1234!", route: "/manager", lookFor: "A KPI row (revenue, gross profit/margin, AI-attributed revenue, low-stock), a low-stock table, profit-by-category, and 'where the AI drove sales' with a 7/30/90/365-day selector." },
  { group: "Manager intelligence (log in)", title: "'Ask your data' admin analyst chat", persona: "Manager", route: "/manager · top 'Ask your data' panel", prompt: "How much revenue did the AI assistant drive, and what's my guardrail-violation rate?", lookFor: "A manager-gated chat quoting real figures — margins, best-sellers, AI cost, CSAT — streaming with live status, reusing the same agent engine as the shopper chat (price guardrail off, analytics tools on)." },
  { group: "Manager intelligence (log in)", title: "AI Operations observability panel", persona: "Manager", route: "/manager · AI Operations section", lookFor: "Agent cost and avg cost/turn, Sonnet-escalation rate, guardrail-block rate, cost-by-model, route-mix and tool-usage bars, plus a recent-turns trace (route, model, tools, tokens, cost, guard pass/fail)." },
  { group: "Manager intelligence (log in)", title: "Multi-agent model router — Haiku triage → Sonnet escalation", persona: "Manager · evidence for the chat you already ran", route: "/manager · AI Operations (route mix)", lookFor: "A cheap Haiku classifier sends simple lookups to the cheap model and escalates project/multimodal/complex turns to Sonnet — your simple 'where are drills?' and the paint-room plan show up split across the route mix and escalation rate." },
  { group: "Manager intelligence (log in)", title: "CSAT analytics + offline chat-quality eval", persona: "Manager", route: "/manager · CSAT section", lookFor: "A 1–5 CSAT average, star histogram and recent comments — plus a deterministic offline eval scoring recent turns on price-faithfulness / relevance / context-use that never blocks live chat (GET /api/v1/analytics/chat-eval)." },
  { group: "Power features & access control", title: "Handwritten stock-sheet OCR intake (human-confirm + audit)", persona: "Staff · staff@buildright.com / StaffDemo1234! · API only", route: "POST /api/v1/media/ocr-stock → POST /api/v1/media/stock/apply", lookFor: "Upload a count sheet → Claude vision OCRs rows, fuzzy-matches each to a SKU with current stock, returns a no-write preview; a separate confirm step applies counts and writes a per-change audit log." },
  { group: "Power features & access control", title: "Admin: order lifecycle + Stripe refunds", persona: "Admin · kept private", route: "/admin · Orders tab", lookFor: "Advance orders through the fulfilment lifecycle and issue full/partial Stripe refunds on paid orders (re-fetched from Stripe and audited) — a privileged tier above manager." },
  { group: "Power features & access control", title: "Admin: menu CRUD with instant vector-embed", persona: "Admin", route: "/admin · Menu tab", lookFor: "Create or delete products; a new item is embedded immediately (best-effort) so the assistant's semantic search finds it right away — and it's still lexically searchable if the embed provider is down." },
  { group: "Power features & access control", title: "RBAC tiers + MCP tool re-export", persona: "Cross-cutting · guest / customer / staff / manager / admin", route: "/login (try each tier) · /manager · /admin", lookFor: "Five JWT/CSRF-protected tiers gate every route and tool, and an MCP server re-exposes the read-only tools to external agents behind the same RBAC boundary — confirm a Shopper is blocked from /manager and /admin." },
];
