"""add_cost_and_attribution

Revision ID: f158c824f9b7
Revises: 1e4d86e1f9ed
Create Date: 2026-06-14 02:06:26.247953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f158c824f9b7'
down_revision: Union[str, Sequence[str], None] = '1e4d86e1f9ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_carts_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_foreign_key('fk_carts_conversation_id', 'conversations', ['conversation_id'], ['id'])

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_cents', sa.Integer(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_source'), ['source'], unique=False)
        batch_op.create_foreign_key('fk_orders_conversation_id', 'conversations', ['conversation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_conversation_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_orders_source'))
        batch_op.drop_index(batch_op.f('ix_orders_conversation_id'))
        batch_op.drop_column('source')
        batch_op.drop_column('conversation_id')

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('cost_cents')

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_carts_conversation_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_carts_conversation_id'))
        batch_op.drop_column('source')
        batch_op.drop_column('conversation_id')

    # ### end Alembic commands ###
